name: fact-ai-cpu
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pillow
  - libtiff
  - ipykernel
  - notebook
  - pip
  - pip:
      - einops
      - transformers
      - jaxtyping
      - pandas
      - datasets
      - wandb
      - accelerate
      - bidict
      - nnsight
      - kornia
      - matplotlib
      - codecarbon
      - seaborn
      - plotly
      - scipy
